# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - script: |
      npm install -g @angular/cli
      npm install
      ng build --prod
    displayName: "npm install and build"

  - script: |
      ng lint
    displayName: "run linting"

  - script: |
      npm run test-pipeline
    displayName: "run testing"

  - script: |
      ng deploy --name="Tom Mean" --email=mail@thomasmean.co.uk --cname=thomasmean.co.uk --repo=https://github.com/ThomasMean/t-mean-angular.git
    displayName: "deploy to github pages"
